# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 174)
        self.lblRuta = QtWidgets.QLabel(parent=Dialog)
        self.lblRuta.setGeometry(QtCore.QRect(20, 30, 351, 21))
        self.lblRuta.setObjectName("lblRuta")
        self.txtRuta = QtWidgets.QLineEdit(parent=Dialog)
        self.txtRuta.setGeometry(QtCore.QRect(20, 60, 351, 22))
        self.txtRuta.setObjectName("txtRuta")
        self.btnExportar = QtWidgets.QPushButton(parent=Dialog)
        self.btnExportar.setGeometry(QtCore.QRect(290, 130, 75, 24))
        self.btnExportar.setObjectName("btnExportar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblRuta.setText(_translate("Dialog", "RUTA"))
        self.btnExportar.setText(_translate("Dialog", "Exportar"))
