# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(427, 262)
        self.lblRuta = QtWidgets.QLabel(parent=Dialog)
        self.lblRuta.setGeometry(QtCore.QRect(20, 120, 391, 21))
        self.lblRuta.setObjectName("lblRuta")
        self.txtRuta = QtWidgets.QLineEdit(parent=Dialog)
        self.txtRuta.setGeometry(QtCore.QRect(20, 150, 391, 22))
        self.txtRuta.setObjectName("txtRuta")
        self.btnNueva = QtWidgets.QToolButton(parent=Dialog)
        self.btnNueva.setGeometry(QtCore.QRect(20, 20, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.btnNueva.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/carpeta.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnNueva.setIcon(icon)
        self.btnNueva.setIconSize(QtCore.QSize(45, 45))
        self.btnNueva.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btnNueva.setObjectName("btnNueva")
        self.btnDescargas = QtWidgets.QToolButton(parent=Dialog)
        self.btnDescargas.setGeometry(QtCore.QRect(320, 20, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.btnDescargas.setFont(font)
        self.btnDescargas.setIcon(icon)
        self.btnDescargas.setIconSize(QtCore.QSize(45, 45))
        self.btnDescargas.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btnDescargas.setObjectName("btnDescargas")
        self.btnDocumentos = QtWidgets.QToolButton(parent=Dialog)
        self.btnDocumentos.setGeometry(QtCore.QRect(220, 20, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.btnDocumentos.setFont(font)
        self.btnDocumentos.setIcon(icon)
        self.btnDocumentos.setIconSize(QtCore.QSize(45, 45))
        self.btnDocumentos.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btnDocumentos.setObjectName("btnDocumentos")
        self.btnEscritorio = QtWidgets.QToolButton(parent=Dialog)
        self.btnEscritorio.setGeometry(QtCore.QRect(120, 20, 90, 80))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(10)
        self.btnEscritorio.setFont(font)
        self.btnEscritorio.setIcon(icon)
        self.btnEscritorio.setIconSize(QtCore.QSize(45, 45))
        self.btnEscritorio.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.btnEscritorio.setObjectName("btnEscritorio")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(250, 210, 160, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancelar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnCancelar.setObjectName("btnCancelar")
        self.horizontalLayout.addWidget(self.btnCancelar)
        self.btnAceptar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnAceptar.setObjectName("btnAceptar")
        self.horizontalLayout.addWidget(self.btnAceptar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblRuta.setText(_translate("Dialog", "RUTA"))
        self.btnNueva.setText(_translate("Dialog", "Nueva carpeta"))
        self.btnDescargas.setText(_translate("Dialog", "Descargas"))
        self.btnDocumentos.setText(_translate("Dialog", "Documentos"))
        self.btnEscritorio.setText(_translate("Dialog", "Escritorio"))
        self.btnCancelar.setText(_translate("Dialog", "Cancelar"))
        self.btnAceptar.setText(_translate("Dialog", "Aceptar"))
