# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(263, 421)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGenerar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGenerar.setGeometry(QtCore.QRect(40, 340, 191, 24))
        self.btnGenerar.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.btnGenerar.setObjectName("btnGenerar")
        self.lblGenero = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblGenero.setGeometry(QtCore.QRect(40, 40, 49, 16))
        self.lblGenero.setObjectName("lblGenero")
        self.lblDni = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDni.setGeometry(QtCore.QRect(40, 140, 49, 16))
        self.lblDni.setObjectName("lblDni")
        self.leDni = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.leDni.setGeometry(QtCore.QRect(40, 160, 191, 22))
        self.leDni.setObjectName("leDni")
        self.cmbGenero = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbGenero.setGeometry(QtCore.QRect(40, 60, 191, 22))
        self.cmbGenero.setObjectName("cmbGenero")
        self.lblCuil = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCuil.setGeometry(QtCore.QRect(40, 240, 49, 16))
        self.lblCuil.setObjectName("lblCuil")
        self.txtCuil = QtWidgets.QLabel(parent=self.centralwidget)
        self.txtCuil.setGeometry(QtCore.QRect(40, 260, 191, 21))
        self.txtCuil.setText("")
        self.txtCuil.setObjectName("txtCuil")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 263, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGenerar.setText(_translate("MainWindow", "Generar"))
        self.lblGenero.setText(_translate("MainWindow", "GENERO"))
        self.lblDni.setText(_translate("MainWindow", "DNI"))
        self.lblCuil.setText(_translate("MainWindow", "CUIL"))
